<div class="row">
    <div class="span8 offset1">
        <div class="floatr">
            <div id="footer">
                <ul class="nav nav-pills">
                    <li> <a href="/site/page/contact.php"> Help </a> </li>
                    <li> <a href="/site/page/about-us.php"> About Us </a> </li>
                    
                    <li> <a href="/site/page/privacy.php">Privacy Policy</a> </li>
                    <li> <a href="/site/page/tos.php">Terms of service</a> </li>
                    <li> <a href="/site/page/ma.php">Merchant Agreement</a> </li>
                    <li> <a href="/site/page/snr.php">Shipping &amp; Refund</a> </li>
                    
                </ul>
            </div>
        </div>
    </div>
</div>


