<div class="row">
    <div class="span8 offset1">
        
        <div id="user-menu">
		    <div class="item"> <a href="/site/page/demo.php">Request a demo</a></div>
		    <div class="item"> <a href="/site/page/price.php">Pricing</a></div>
		    <div class="item"> <a href="/site/page/explain.php">How it works</a></div>
		     <div class="item"> <a href="/site/page/contact.php">Support</a></div>
		</div>

    </div>
</div> <!-- top unit -->
