
<div class="row">
    <div class="span8 offset1">
        <div id="top-unit">
            <h5 class="faded-text"> <?php echo G_APP_TAGLINE ?></h5>
        </div>

        <style>
        	/* @inpage @hardcoded */
        	#user-menu .item {
        		float: left;
				border-bottom: 3px solid #28C;
				padding: 0 4px;
				margin: 1px 12px 0;
				font-weight: bold;
        	}

        	#user-menu .item a {
        		color : #333 ;
                text-decoration: none ;
        	}

            #user-menu .item a:hover {
                color : #b1b1b1;
                text-decoration: none ;
            }


        </style>
        <div id="user-menu">
		    <div class="item"> <a href="/app/dashboard.php">Dashboard</a></div>
		    <div class="item"> <a href="/app/show-page.php">Manage pages</a></div>
		</div>

    </div>
</div> <!-- top unit -->



