
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a> <!-- 3bars for smaller screens -->
            <a class="brand" href="/ghost/canvas/"><?php echo G_APP_NAME ?><span class="beta">&nbsp;private beta</span> </a>

            <div class="nav-collapse">
                <ul class="nav">
                    <li> <a href="/ghost/canvas/"><i class="icon-home"></i>&nbsp;Home</a></li>
                </ul>
                
            </div>

        </div>

    </div>
</div> <!-- default toolbar -->

