<?php

define("APP_LIB_PATH", 
            "/home/rjha/code/github/webgloo/lib/ext/sendgrid-php,". 
            "/home/rjha/code/github/webgloo/lib/ext,". 
            "/home/rjha/code/github/webgloo/lib,". 
            "/home/rjha/code/github/fsales/lib") ;

define("APP_CLASS_LOADER", 
            "/home/rjha/code/github/webgloo/lib/com/indigloo/class_loader.inc") ;

define("APP_CONFIG_PATH", "/var/www/apps/fs_config.ini");
define("APP_WEB_DIR", "/var/www/vhosts/www.favsales.com/htdocs") ;
define("WEBGLOO_LIB_ROOT","/home/rjha/code/github/webgloo/lib");

?>
