



9 Jan 2013
-------------

+ point www.favsales.com to your server IP
+ create a new Nginx vhost 
+ copy nginx vhost file to /etc/nginx/sites-enabled/ folder
 - check the vhost file
+ create a symlink from /var/www/vhosts/www.favsales.com/htdocs => code web/ folder
    $ sudo mkdir www.favsales.com
    $ sudo ln -nfs ~/code/github/fsales/web /var/www/vhosts/www.favsales.com/htdocs


+ copy fs-app.inc and fs_config.ini to /var/www/apps folder 

$ sudo cp ~/code/github/fsales/conf/fs-app.inc /var/www/apps/.
$ sudo cp ~/code/github/fsales/conf/fs_config.ini /var/www/apps/.

+ fs-app.inc file : make sure of locations
+ fs_configi.ini
 - check values
 - remove unwanted stuff

 + session lifetime/backend - 
 	86400 - for 1 DAY
 	7 Days - 604800 seconds

+ change facebook appId and appSecret

+ create web/compiled folder : change ownership of this folder to www-data
$ mkdir compiled
$ sudo chown -R www-data:www-data compiled/

+ copy gitignore file into git repo ROOT
 .gitignore


+ @todo - remove 3mik addresses for sendgrid stuff in config  
+ create database fsdb1
+ load schema.sql into fsdb1


+ restart NGINX
 - NGINX 502 : Because PHP script may have been failing
 - DB needs user access on 10.178.225.240 IP as well
 - make sure mysql user password is correct

+ logrotate - add an entry for fs-app.log
+ Install cron script to pull comments (every 11 mins)









